# Generated by Django 6.1 on 2026-09-14 23:07
# Editado a mano: se inserta un paso de datos (RunPython) entre la creacion
# de FormaPago y el borrado de Compra.metodo_pago, para no perder el metodo
# de pago de las compras ya registradas.

import django.db.models.deletion
from django.db import migrations, models


def migrar_metodo_pago_a_formas_pago(apps, schema_editor):
    """Convierte el metodo_pago (unico) de cada Compra existente en su
    primera FormaPago, con el monto igual al total de esa compra."""
    Compra = apps.get_model('core', 'Compra')
    Venta = apps.get_model('core', 'Venta')
    FormaPago = apps.get_model('core', 'FormaPago')
    for compra in Compra.objects.all():
        total = Venta.objects.filter(compra=compra).aggregate(total=models.Sum('total'))['total'] or 0
        FormaPago.objects.create(compra=compra, tipo=compra.metodo_pago, monto=total)


def eliminar_formas_pago(apps, schema_editor):
    FormaPago = apps.get_model('core', 'FormaPago')
    FormaPago.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_venta_metodo_pago_compra_venta_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=15)),
                ('monto', models.PositiveIntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='core.compra')),
            ],
        ),
        migrations.RunPython(migrar_metodo_pago_a_formas_pago, eliminar_formas_pago),
        migrations.RemoveField(
            model_name='compra',
            name='metodo_pago',
        ),
    ]
